---
- name: NSOT Tester
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    site_id: 1
    URL: "http://10.38.9.39:8991/api/sites/{{ site_id }}" 
    encr_snet: "10.119.0.0/24"
    encr_prefix: "/28"
  tasks:
    ############
    # ITERABLE #
    ############
    - name: Collect all the iterables
      action: uri url={{ URL }}/iterable  return_content=yes
      register: result

    - name: Debug
      debug: var=result.content

    - name: Identify the ID of the cryptomap_counter
      set_fact: iterable="{{ item.id }}"
      when:  item.name ==  "cryptomap_counter"
      with_items: result.content


    - name: Collect the next available cryptomap number
      action: uri url={{ URL }}/iterable/{{ iterable }}/next_value 
      register: next_val


    - name: Generate an unique ID to identify the play
      set_fact: uid={{ bu_name | to_uuid }}

    - name: Create the json body to allocate the itervalue
      template: 
        src: itervalue.j2
        dest: /vagrant/network_ansible_playbooks/iterval_create.json

    - name: Allocate the next available cryptomap number 
      uri:
        url: http://10.38.9.39:8991/api/sites/{{ site_id }}/itervalue/
        method: POST 
        return_content: yes 
        HEADER_Content-Type: "application/json"
        body: "{{ lookup('file','iterval_create.json') }}"
        status_code: 201
        body_format: json
      
    ##########
    # PREFIX #
    ##########
    - name: Collect the next available encryption domainc
      action: uri url={{ URL }}/networks/{{ encr_snet }}/next_network/?prefix_length=28
      register: encry_domain
      tags: prefix
      
    - name: Create the json body to allocate the itervalue
      template: 
        src: subnet_create.j2
        dest: /vagrant/network_ansible_playbooks/subnet_create.json
      tags: prefix


    - name: Allocate the next available encryption domain
      uri:
        url: http://10.38.9.39:8991/api/sites/{{ site_id }}/networks/
        method: POST 
        return_content: yes 
        HEADER_Content-Type: "application/json"
        body: "{{ lookup('file','subnet_create.json') }}"
        status_code: 201
        body_format: json
      tags: prefix
 


